import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "./(Components)/Nav";
import Link from "next/link";
export const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br bg-fixed from-accentColor/20 to-neutral-500 flex flex-col items-center h-screen   ${roboto.className} ${geistSans.variable} ${geistMono.variable} box-border antialiased`}
      >
        <Nav />

        <main className=" p-10 flex flex-col justify-center items-start flex-1 my-1 w-[90%] shadow-sm rounded shadow-black ">
          {children}
          {/* <div className="fixed  bottom-[-30%] -z-10 blur-[500px] left-[-10%] w-[50%] aspect-square bg-accentColor rounded-full"></div> */}
        </main>
        <footer className="text-secTextColor text-lg mt-10">
          &copy; 2025 Designed and Developed by{" "}
          <Link
            href={"https://www.linkedin.com/in/mhmdawad/"}
            target="_blank"
            className="text-blue-800 hover:underline"
          >
            Mohammed Awad
          </Link>
          . All rights reserved.
        </footer>
      </body>
    </html>
  );
}
